### ISSUE TITLE
data.callback

### ISSUE THREAD

**Issue by czarnndz** [open-pay/openpay-node#4]
Hola que tal, integré openpay tal y como marcaba la documentación en: https://www.openpay.mx/docs/card-charge.html

El detalle es que al querer hacer una prueba me arroja el siguiente error:

`TypeError: data.callback is not a function
    at Request._callback (/var/task/node_modules/openpay/lib/openpay.js:605:10)
    at Request.self.callback (/var/task/node_modules/openpay/node_modules/request/request.js:123:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/var/task/node_modules/openpay/node_modules/request/request.js:877:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/var/task/node_modules/openpay/node_modules/request/request.js:828:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)`
 

Lo que parece ser un error dentro de la biblioteca de openpay.

Encontré un post sobre esto aquí:
https://disqus.com/home/discussion/openpay/openpay_cargo_a_tarjeta_96/

Donde reportaron el mismo error, pero al parecer no han podido solucionarlo o se deba a algún otro problema.

Saludos

**Comment by igrijalva** [comment]
Que tal Cesar,

Gracias por contactarnos, me puedes ayudar con el nombre de la función que
estas ejecutando al momento del error, y si te es posible compartirnos la
sección de código en donde haces este llamado.




Saludos.




<http://www.openpay.mx>   *Israel Grijalva  | Desarrollo*
blog.openpay.mx
@OpenpayMX <https://twitter.com/OpenpayMX>   Teléfono: +52 (55) 4170.3567
<%2B52%20%2855%29%204170.3567%20ext.1507>
Email: israel.grijalva@openpay.mx
<http://www.openpay.mx>

2017-10-29 12:42 GMT-06:00 Cesar Nandez <notifications@github.com>:

**Comment by igrijalva** [comment]
Seguimos a tus órdenes

**Comment by czarnndz** [comment]
La función es: openpay.customers.charges.create()

Saludos

**Comment by hecmonn** [comment]
Ya hay solución de esto?

**Comment by eleazargame** [comment]
create : function (customerId, data, callback)

Esta funciín dentro de la librería recibe 3 parametros.
Por eso sale el error ya que al mandarle solo 2 el callback esta indefinido.. Espero les sirva la respuesta.
